language: python

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt -qq update
  - sudo apt install -y ffmpeg
install:
  - pip install .
before_script:
  - cd complexity_science
script:
  - python -m pytest
